name: Auto Create Pull Request

on:
  push:
    branches:
      - jahanzaib_dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: jahanzaib_dev
          base: main
          title: "Auto PR from jahanzaib_dev"
          body: "This PR is created automatically"
